### ISSUE TITLE
[BUG] La flèche bleu

### ISSUE THREAD

**Issue by ghost** [TuMeNiaises/public#5]
**Description**
La flèche bleu du début ne disparait pas 
et n'a pas d'interaction.

**Plateforme:**
 - [tsé ] Windows
 - [ ] Linux
 - [ ] Fureteur web

**Étapes pour reproduire**

1. Commencer une partie
2. Gagner le premier combat pour faire disparaître l'ennemi.

**Comportement attendu**
Soit qu'elle disparaît.
Soit qu'elle a une raison d'être présente?

**Capture d'écran**
![La flèche bleu du début ne disparait pas et n'a pas d'interaction](https://user-images.githubusercontent.com/9667407/82742030-f43a4900-9d26-11ea-9d88-fbdf1a10a692.png)

**Commentaire additionnels**
Turn down for what?

**Comment by Hect0rr** [comment]
En effet ça n'avait pas d'utilisation. Je vais fermé l'issue, car au moment du release il y a juste rien qui était implémenté pour cette flèche.
